#!/bin/bash

args=( "$@" )
extra_arguments=""

for (( i=1; i<=$(( $# -1 )); i++ ))
do
    extra_arguments=${extra_arguments}" ${args[$i]}"
done

export TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
$1/build/tools/make-standalone-toolchain.sh \
    --toolchain=arm-linux-androideabi-4.7 \
    --arch=arm \
    --install-dir=$TOOLCHAIN \
    --platform=android-9
export PATH=$TOOLCHAIN/bin:$PATH
export AR=arm-linux-androideabi-ar
export CC=arm-linux-androideabi-gcc
export CXX=arm-linux-androideabi-g++
export LINK=arm-linux-androideabi-g++

./configure \
    --without-snapshot \
    --dest-cpu=arm \
    --dest-os=android \
    $extra_arguments
