.TH nodejs-repl 1 "4 February 2010"
.
.SH NAME
.
nodejs-repl - Nodejs read-eval-print-loop
.SH SYNOPSIS
.B echo
[\fISHORT-OPTION\fR]... [\fISTRING\fR]...
.
.SH DESCRIPTION
.
\fInodejs-repl\fP provides a read eval print loop for nodejs.
.P
To provide a better interface, \fInodejs-repl\fP uses rlwrap.
.
.SH "SEE ALSO"
.
.BR nodejs(1),
.BR rlwrap(1)
